import 'package:flutter/material.dart';
import 'package:flutterapp/caregiverapp/generatedcomposerwidget/generated/GeneratedPrimery3itemsWidget.dart';
import 'package:flutterapp/caregiverapp/generatedcomposerwidget/generated/GeneratedSectionWidget1.dart';
import 'package:flutterapp/caregiverapp/generatedcomposerwidget/generated/GeneratedSectionWidget2.dart';
import 'package:flutterapp/caregiverapp/generatedcomposerwidget/generated/GeneratedTopPrimeryWidget.dart';
import 'package:flutterapp/caregiverapp/generatedcomposerwidget/generated/GeneratedSystemnavWidget.dart';
import 'package:flutterapp/caregiverapp/generatedcomposerwidget/generated/GeneratedSectionWidget.dart';

/* Frame Composer
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComposerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 20, 25, 39),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 80.0,
                child: GeneratedTopPrimeryWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 184.0,
                child: GeneratedSectionWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 184.0,
                child: GeneratedSectionWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 359.0,
                height: 184.0,
                child: GeneratedSectionWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 626.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 14.0,
                child: GeneratedSystemnavWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedPrimery3itemsWidget(),
              )
            ]),
      ),
    ));
  }
}
